### ISSUE TITLE
Scalar DB Schema Tool fails due to parser tool updates.

### ISSUE THREAD

**Issue by yuriken27** [scalar-labs/scalardb#19]
Scalar DB Schema Tools can not be "make".

The reason is that the IF of the Parser being used by the Tool has changed, and since there is an argument with no argument, an error occurs at make time.

■Error detail

> $ cd tools/schema
> $ make
> go get github.com/alecthomas/kingpin
> go get github.com/alecthomas/participle
> 1. _/home/ec2-user/scalardb/tools/schema/internal/parser
> internal/parser/parser.go:42:68: not enough arguments in call to participle.UseLookahead
>     have ()
>     want (int)
> make: *** <build> エラー 2

■Parser Tool
https://github.com/alecthomas/participle

**Comment by scalarindetail** [comment]
The problem was caused because the [parser library](https://github.com/alecthomas/participle) released an update that contained breaking changes (the coded was working with 1.0 but the 2.0 was released 20 days ago). 

Libraries are imported with go-get but it does not allow to specify a version or a branch tag.
```
install:
	go get github.com/alecthomas/kingpin
	go get github.com/alecthomas/participle
```
To fix import the dependencies with fixed version, we could use a tool such as [dep](https://github.com/golang/dep). 
The make would become:
```
install:
        go get -u github.com/golang/dep/cmd/dep
        dep ensure (will download the library for the project)
```

**Comment by feeblefakie** [comment]
@yuriken27  I think this is now fixed with https://github.com/scalar-labs/scalardb/commit/74dba96afd21bf349e0a8e558ca0c9420caa8279 .

**Comment by yuriken27** [comment]
I checked again and this problem was corrected.
Schema Tool works correctly.
